# Generated by Django 4.2.7 on 2025-03-29 09:18

from django.db import migrations, models
import django.db.models.deletion
import optimizer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompositionRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=optimizer.models.OverwriteStorage(), upload_to='composition_requirements/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=optimizer.models.OverwriteStorage(), upload_to='scrap_data/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OptimizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('total_products', models.IntegerField(blank=True, null=True)),
                ('composition_requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.compositionrequirements')),
                ('scrap_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.scrapdata')),
            ],
        ),
        migrations.CreateModel(
            name='OptimizationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='optimizer.optimizationresult')),
            ],
        ),
        migrations.CreateModel(
            name='BatchProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='optimizer.optimizationbatch')),
            ],
        ),
    ]
